The 101-lazy_matrix_mul module
======================

Using lazy_matrix_mul
-------------------

SETUP:
	>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

	Test Cases::

	>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
	[[7, 10], [15, 22]]

	>>> mat_a = [[3, 1, 3], [2, 5, 9], [9, 1, 0]]
	>>> mat_b = [[7, -1, 2], [2, -1, -9], [-3, -3, 0]]
        >>> lazy_matrix_mul(mat_a, mat_b)
	[[14, -13, -3], [-3, -34, -41], [65, -10, 9]]

	>>> lazy_matrix_mul([[1, 2, 3]], [[7], [2], [1]])
	[[14]]

	>>> lazy_matrix_mul([[8, 12, 3]], None)
	Traceback (most recent call last):
		Random shii        	      ...
	TypeError: Object arrays are not currently supported

	>>> lazy_matrix_mul((3, 4, 0), [[9.2], [2.2], [4.7]])
	[36.4]

Passing a matrix with an empty list

    >>> lazy_matrix_mul([[12, 12, 12], [], [14, 14, 14]], [[2], [3], [8]])
    Traceback (most recent call last):
    	      ...
    ValueError: setting an array element with a sequence.

Passing a matrix which its rows have different size

    >>> lazy_matrix_mul([[2, 2, 2], [4, 4, 4]], [[2], [3, 3]])
    Traceback (most recent call last):
    	      ...
    ValueError: setting an array element with a sequence.

Passing two matrix that can't be multiplied

    >>> lazy_matrix_mul([[5, 2, 3], [7, 13, 2], [1, 0, 3]], [[2, 3], [6, 9]])
    Traceback (most recent call last):
    	      ...
    ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

Missing one argument

    >>> lazy_matrix_mul([[1, 2]])
    Traceback (most recent call last):
    	      ...
    TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

Missing arguments

    >>> lazy_matrix_mul()
    Traceback (most recent call last):
    	      ...
    TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
